import { Puzzle } from './types';

const BASE_USER = `type User = { name: string; age: number; email: string; isAdmin: boolean };`;

export const puzzles: Puzzle[] = [
  {
    id: 'keyof-basic',
    title: '問題1: keyof',
    description: 'User型のキー名だけのUnion型を作ってください。',
    targetCodeDisplay: 'type Result = keyof User',
    baseTypeSource: BASE_USER,
    typeParams: [],
    refNames: ['User'],
    testCases: [{ args: '', expected: 'keyof User' }],
  },
  {
    id: 'pick-basic',
    title: '問題2: Pick',
    description: "User型から name と email だけを取り出した型を作ってください。",
    targetCodeDisplay: "type Result = Pick<User, 'name' | 'email'>",
    baseTypeSource: BASE_USER,
    typeParams: [],
    refNames: ['User'],
    testCases: [{ args: '', expected: "Pick<User, 'name' | 'email'>" }],
  },
  {
    id: 'template-literal-basic',
    title: '問題3: Template Literal',
    description: "User型のキー名の末尾に '-id' を付けたUnion型を作ってください。",
    targetCodeDisplay: 'type Result = `${keyof User}-id`',
    baseTypeSource: BASE_USER,
    typeParams: [],
    refNames: ['User'],
    testCases: [{ args: '', expected: '`${keyof User}-id`' }],
  },
  {
    id: 'partial-basic',
    title: '問題4: Partial',
    description: 'User型の全フィールドをオプショナルにした型を作ってください。\nヒント: Mapped Type の「optional化」変換を使います。',
    targetCodeDisplay: 'type Result = { [K in keyof User]?: User[K] }',
    baseTypeSource: BASE_USER,
    typeParams: [],
    refNames: ['User'],
    testCases: [{ args: '', expected: '{ [K in keyof User]?: User[K] }' }],
  },
  {
    id: 'conditional-basic',
    title: '問題5: Conditional Type',
    description: "User['isAdmin'] の型が boolean なら true、そうでなければ false を返す型を作ってください。\nヒント: Conditional Type と T[K] を組み合わせます。",
    targetCodeDisplay: "type Result = User['isAdmin'] extends boolean ? true : false",
    baseTypeSource: BASE_USER,
    typeParams: [],
    refNames: ['User'],
    testCases: [{ args: '', expected: "User['isAdmin'] extends boolean ? true : false" }],
  },
  {
    id: 'infer-basic',
    title: '問題6: infer',
    description: "タプル [string, number] の先頭要素の型を infer で取り出してください。\nヒント: Conditional Type の extends 句にタプルと infer を置きます。",
    targetCodeDisplay: 'type Result = [string, number] extends [infer First, number] ? First : never',
    baseTypeSource: BASE_USER,
    typeParams: [],
    refNames: ['User'],
    testCases: [{ args: '', expected: '[string, number] extends [infer First, number] ? First : never' }],
  },
  {
    id: 'tc-4-pick',
    title: 'TC #4: MyPick',
    description: "type-challenges #4。組み込みの Pick<T, U> を自作してください。T の中から U に指定したキーだけを取り出した型を作ります。\nヒント: Mapped Type で「keys: U」「source: T」を指定します。\n注意: Mapped Type のイテレータ名は本ツールでは K に固定されているため、型パラメータ名に K は使えません。",
    targetCodeDisplay: 'type MyPick<T, U extends keyof T> = { [K in U]: T[K] }',
    baseTypeSource: 'interface Todo { title: string; description: string; completed: boolean }',
    typeParams: [{ name: 'T' }, { name: 'U', constraint: 'keyof T' }],
    refNames: ['T', 'U'],
    testCases: [
      { args: "Todo, 'title'", expected: '{ title: string }' },
      { args: "Todo, 'title' | 'completed'", expected: '{ title: string; completed: boolean }' },
    ],
  },
  {
    id: 'tc-18-length',
    title: 'TC #18: Length',
    description: "type-challenges #18。タプル型 T を受け取り、その要素数(length)を返す型を作ってください。\nヒント: T['length'] で取り出せます。",
    targetCodeDisplay: "type Length<T extends readonly any[]> = T['length']",
    baseTypeSource: '',
    typeParams: [{ name: 'T', constraint: 'readonly any[]' }],
    refNames: ['T'],
    testCases: [
      { args: "readonly ['tesla', 'model 3', 'model X', 'model Y']", expected: '4' },
      { args: "readonly ['FALCON 9', 'FALCON HEAVY', 'DRAGON', 'STARSHIP', 'HUMAN SPACEFLIGHT']", expected: '5' },
    ],
  },
  {
    id: 'tc-268-if',
    title: 'TC #268: If',
    description: "type-challenges #268。真偽値 C を受け取り、C が true なら T を、false なら F を返す型を作ってください。\nヒント: Conditional Type で C extends true ? T : F。",
    targetCodeDisplay: 'type If<C extends boolean, T, F> = C extends true ? T : F',
    baseTypeSource: '',
    typeParams: [{ name: 'C', constraint: 'boolean' }, { name: 'T' }, { name: 'F' }],
    refNames: ['C', 'T', 'F'],
    testCases: [
      { args: "true, 'a', 'b'", expected: "'a'" },
      { args: "false, 'a', 2", expected: '2' },
    ],
  },
  {
    id: 'tc-43-exclude',
    title: 'TC #43: MyExclude',
    description: "type-challenges #43。組み込みの Exclude<T, U> を自作してください。Union型 T から U に含まれるメンバーを除いた型を作ります。\nヒント: 裸の型パラメータを Conditional Type の check に置くと、Union は自動的に分配されます。",
    targetCodeDisplay: 'type MyExclude<T, U> = T extends U ? never : T',
    baseTypeSource: '',
    typeParams: [{ name: 'T' }, { name: 'U' }],
    refNames: ['T', 'U'],
    testCases: [
      { args: "'a' | 'b' | 'c', 'a'", expected: "'b' | 'c'" },
      { args: "'a' | 'b' | 'c', 'a' | 'b'", expected: "'c'" },
      { args: 'string | number | (() => void), Function', expected: 'string | number' },
    ],
  },
  {
    id: 'tc-7-readonly',
    title: 'TC #7: MyReadonly',
    description: "type-challenges #7。組み込みの Readonly<T> を自作してください。T の全プロパティを readonly にした型を作ります。\nヒント: Mapped Type の「readonly化」変換を使います。",
    targetCodeDisplay: 'type MyReadonly<T> = { readonly [K in keyof T]: T[K] }',
    baseTypeSource: 'interface Todo1 { title: string; description: string; completed: boolean; meta: { author: string } }',
    typeParams: [{ name: 'T' }],
    refNames: ['T'],
    testCases: [
      { args: 'Todo1', expected: 'Readonly<Todo1>' },
    ],
  },
  {
    id: 'tc-11-tuple-to-object',
    title: 'TC #11: TupleToObject',
    description: "type-challenges #11。文字列や数値からなるタプル型 T を受け取り、各要素をキーにも値にも持つオブジェクト型を作ってください。\nヒント: Mapped Type の「キー集合」に T[number] を、「カスタム値に切替」で値に K 自身を置きます。",
    targetCodeDisplay: "type TupleToObject<T extends readonly (string | number | symbol)[]> = { [K in T[number]]: K }",
    baseTypeSource: '',
    typeParams: [{ name: 'T', constraint: 'readonly (string | number | symbol)[]' }],
    refNames: ['T'],
    testCases: [
      { args: "readonly ['tesla', 'model 3', 'model X', 'model Y']", expected: "{ tesla: 'tesla'; 'model 3': 'model 3'; 'model X': 'model X'; 'model Y': 'model Y' }" },
      { args: 'readonly [1, 2, 3, 4]', expected: '{ 1: 1; 2: 2; 3: 3; 4: 4 }' },
      { args: "readonly [1, '2', 3, '4']", expected: "{ 1: 1; '2': '2'; 3: 3; '4': '4' }" },
    ],
  },
  {
    id: 'tc-14-first',
    title: 'TC #14: First',
    description: "type-challenges #14。配列 T を受け取り、その先頭要素の型を返す型を作ってください。空配列の場合は never を返します。\nヒント: Conditional Type の extends 句に [infer First, ...infer Rest] を置きます。",
    targetCodeDisplay: 'type First<T extends any[]> = T extends [infer F, ...infer R] ? F : never',
    baseTypeSource: '',
    typeParams: [{ name: 'T', constraint: 'any[]' }],
    refNames: ['T'],
    testCases: [
      { args: '[3, 2, 1]', expected: '3' },
      { args: '[() => 123, { a: string }]', expected: '() => 123' },
      { args: '[]', expected: 'never' },
      { args: '[undefined]', expected: 'undefined' },
    ],
  },
  {
    id: 'tc-533-concat',
    title: 'TC #533: Concat',
    description: "type-challenges #533。2つの配列 T, U を受け取り、それらを連結した配列型を作ってください。\nヒント: Tuple の中に Rest ブロックを2つ並べます: [...T, ...U]。",
    targetCodeDisplay: 'type Concat<T extends readonly unknown[], U extends readonly unknown[]> = [...T, ...U]',
    baseTypeSource: '',
    typeParams: [{ name: 'T', constraint: 'readonly unknown[]' }, { name: 'U', constraint: 'readonly unknown[]' }],
    refNames: ['T', 'U'],
    testCases: [
      { args: '[], []', expected: '[]' },
      { args: '[], [1]', expected: '[1]' },
      { args: '[1, 2], [3, 4]', expected: '[1, 2, 3, 4]' },
      { args: "['1', 2, '3'], [false, boolean, '4']", expected: "['1', 2, '3', false, boolean, '4']" },
    ],
  },
  {
    id: 'tc-3057-push',
    title: 'TC #3057: Push',
    description: "type-challenges #3057。配列 T の末尾に要素 U を追加した配列型を作ってください。\nヒント: [...T, U] の形になります。",
    targetCodeDisplay: 'type Push<T extends unknown[], U> = [...T, U]',
    baseTypeSource: '',
    typeParams: [{ name: 'T', constraint: 'unknown[]' }, { name: 'U' }],
    refNames: ['T', 'U'],
    testCases: [
      { args: '[], 1', expected: '[1]' },
      { args: "[1, 2], '3'", expected: "[1, 2, '3']" },
      { args: "['1', 2, '3'], boolean", expected: "['1', 2, '3', boolean]" },
    ],
  },
  {
    id: 'tc-3060-unshift',
    title: 'TC #3060: Unshift',
    description: "type-challenges #3060。配列 T の先頭に要素 U を追加した配列型を作ってください。\nヒント: [U, ...T] の形になります。",
    targetCodeDisplay: 'type Unshift<T extends unknown[], U> = [U, ...T]',
    baseTypeSource: '',
    typeParams: [{ name: 'T', constraint: 'unknown[]' }, { name: 'U' }],
    refNames: ['T', 'U'],
    testCases: [
      { args: '[], 1', expected: '[1]' },
      { args: '[1, 2], 0', expected: '[0, 1, 2]' },
      { args: "['1', 2, '3'], boolean", expected: "[boolean, '1', 2, '3']" },
    ],
  },
  {
    id: 'tc-3312-parameters',
    title: 'TC #3312: MyParameters',
    description: "type-challenges #3312。組み込みの Parameters<T> を自作してください。関数型 T の引数の型をタプルとして取り出します。\nヒント: Function ブロックの params スロットに infer P を置き、Conditional Type の extends 句で使います。",
    targetCodeDisplay: 'type MyParameters<T extends (...args: any[]) => any> = T extends (...args: infer P) => any ? P : never',
    baseTypeSource: '',
    typeParams: [{ name: 'T', constraint: '(...args: any[]) => any' }],
    refNames: ['T'],
    testCases: [
      { args: '(arg1: string, arg2: number) => void', expected: '[string, number]' },
      { args: "(arg1: boolean, arg2: { name: 'foo' }) => void", expected: "[boolean, { name: 'foo' }]" },
      { args: '() => void', expected: '[]' },
    ],
  },
];
